export const popular = [
  {
    id: '1',
    title: 'Cactus 1',
    price: 'R$ 39,90',
    description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
    height: 15,
    width: 8,
    category: 'Interna',
    type: 'Pequeno',
    plant: 'Cactus',
    isFavorited: true,
  },
  {
    id: '2',
    title: 'Cactus 2',
    price: 'R$ 23,50',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur',
    height: 42,
    width: 20,
    category: 'Externa',
    type: 'Grande',
    plant: 'Cactus',
    isFavorited: false,
  },
  {
    id: '3',
    title: 'Flores 1',
    price: 'R$ 54,90',
    description: 'ut I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.',
    height: 32,
    width: 16,
    category: 'Externa',
    type: 'Grande',
    plant: 'Flores',
    isFavorited: false,
  },
]